### ISSUE TITLE
iOSとAndroidの動作確認手順の見直し

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/mynumbercard-idp#10]
## ngrokについて

ローカルでの動作確認の手順では複数ポートのフォワーディングの必要性からngrokの有料版利用が必須となっていますが、
実際には80番ポートのフォワーディングのみで動作確認を行えることがわかりました。

無償で実行できるのならば、無償で実行する方法をとった方が良いと思いますので、
1つのポート（80番）のみのフォワーディンでの手順への書き換えが必要だと思われます。

**Comment by ryo-ma** [comment]
#67 #63 で対応済み
